site_name: Math Mate

theme:
  name: material
  palette:
    primary: red
    accent: brown

nav:
  - Inicio: index.md
  - Nustros servicios: servicios.md
  - Integrantes: integrantes/integrantes.md
  - Contacto: contacto.md

use_directory_urls: false

plugins:
  - mkdocstrings
  - search

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - mdx_math


